version: "3.8"

services:
  backend:
    image: gamjachoi/game-set-backend:latest
    container_name: game-set-backend
    restart: always

    ports:
      - "8080:8080"

    environment:
      SPRING_PROFILES_ACTIVE: prod
      SERVER_PORT: 8080

      DB_URL: ${DB_URL}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}

      MAIL_USERNAME: ${MAIL_USERNAME}
      MAIL_PASSWORD: ${MAIL_PASSWORD}

      JWT_SECRET: ${JWT_SECRET}

      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}

      AWS_ACCESS_KEY: ${AWS_ACCESS_KEY}
      AWS_SECRET_KEY: ${AWS_SECRET_KEY}
      AWS_BUCKET_NAME: ${AWS_BUCKET_NAME}

  frontend:
    image: gamjachoi/game-set-frontend:latest
    container_name: game-set-frontend
    restart: always

    ports:
      - "80:80"

    depends_on:
      - backend
