spring.application.name=game_set_back

server.port=${SERVER_PORT:8080}

# DataSource (MySQL)
spring.datasource.url=jdbc:mysql://my-database.cb48k4csqar4.ap-northeast-2.rds.amazonaws.com:3306/game_db?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
spring.datasource.username=admin
spring.datasource.password=admin.1122
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# SQL
logging.level.com.test.withdayback.mapper=debug

# email setting
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=gamjachoi00@gmail.com
spring.mail.password=
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

jwt.secret=G7mQ2xA9kL5vP8zR1tN6yF4sH0cW3eB9uD7iK2oX5rJ8qL6